### ISSUE TITLE
Error establishing connection

### ISSUE THREAD

**Issue by ghost** [brainboxdotcc/windows-bot-template#4]

**Comment by braindigitalis** [comment]
ugh, discord moment.

I've pushed a fix for this to the `master` branch, thanks very much for the report!

**Comment by Cyte1** [comment]
Thanks, can apply fix on this project?

**Comment by braindigitalis** [comment]
just give it 30 minutes and it should automatically pull across from DPP repo

**Comment by Cyte1** [comment]
Alright, Have a good day!
